name: Test deployment with Environment

on:
  workflow_dispatch:
    
jobs:
  Build:
    runs-on: self-hosted

    steps:
      - run: |
          az login --identity -u $MSI_CLIENT_ID
          az account show
          az group list --query '[].name' -o tsv
        name: Execute az cli sample commands

  DeployDev:
    name: Deploy to Dev 
    needs: [Build]
    runs-on: self-hosted
    environment: 
      name: Development
    steps:
      - name: Deploy
        run: echo I am deploying to dev! 
        
  DeployProd:
    name: Deploy to Production 
    needs: [DeployDev]
    runs-on: self-hosted
    environment: 
      name: Production
    steps:
      - name: Deploy
        run: echo I am deploying to prod! 
